import { readdirSync, readFileSync, writeFileSync } from "node:fs";

// All migrations in order, as one file to paste into the Supabase SQL editor of an empty project.
const dir = "supabase/migrations";
const files = readdirSync(dir).filter((f) => f.endsWith(".sql")).sort();
const parts = files.map((f) => `-- migration: ${f}\n${readFileSync(`${dir}/${f}`, "utf8").trim()}\n`);
writeFileSync(
  "supabase/deploy.sql",
  [
    "-- MAWHIBA database, generated by `npm run db:bundle` from supabase/migrations. Do not edit by hand.",
    "-- Paste into the Supabase SQL editor of an EMPTY project and run once. Then run `npm run seed:deploy`.",
    "",
    ...parts,
  ].join("\n"),
);
console.log(`✔ supabase/deploy.sql written (${files.length} migrations)`);
